@startuml
:タイトル(エンターキー押す);
if (メニュー) then (部屋を作る)
  :部屋設定(部屋番号, マッチング方, ルール);
else (部屋に入る)
  if (マッチング方) then (ランダム)
    :ランダムで部屋に入る;
  else (指定)
    :部屋番号を入力;
    endif
endif
:マッチング画面;
if (マッチング) then (マッチング成功)
  :ゲーム画面;
else (マッチング失敗)
  :マッチング画面;
@enduml